### ISSUE TITLE
Feature: Embed exhibit into walking tour item

### ISSUE THREAD

**Issue by evan-lauer** [DigitalCarleton/WalkingTour#11]
Add the ability to embed an exhibit into an item on a walking tour, so that item could link to more detailed materials about the item.

**Comment by evan-lauer** [comment]
[Feature request]

I can't label this b/c I'm not a contributor.

**Comment by apjmason** [comment]
Do this from the tour create admin site. Modify the form to add a "Link Exhibit" action to each item in the walking tour form, that calls up a box similar to the Add Item but searches Exhibits instead.

![image](https://github.com/DigitalCarleton/MallMap/assets/10544799/437aff55-f822-4e7c-9359-bb81c458bf5a)

These links would be added on the public side as a button on the tour stop modal, alongside the See Full Details button

**Comment by tutingjun** [comment]
In tour creation, make sure there are no duplicated items
