### ISSUE TITLE
Multiple Tours

### ISSUE THREAD

**Issue by bierleya** [DigitalCarleton/WalkingTour#2]
One of the next steps to take with this plugin would be to fix the functionality of having multiple walking tours. Currently, multiple tours can be added, but they do not show up as separate tours on the map (ie. tour 1 has points (A, B) and tour 2 has points (C, D), and the map currently links (A, B, C, D) into one tour with four points instead of two tours with two points). 

It seems like the problem begins in the filterAction() function in the IndexController.php file, where the line 

$request_tour_id = $this->_request->getParam('tourType');

currently returns NULL, when it should have a tour_id value. Because of this, all tour items get fetched from the database instead of just the items for a specific tour, causing all of the tour items to be grouped into one tour.

**Comment by evan-lauer** [comment]
This is fixed in the alvin-updates branch. Closing this for now
